[goldmark]
  [goldmark.renderer]
    unsafe = true
  [goldmark.parser]
    [goldmark.parser.attribute]
      block = true
      title = true

[highlight]
  codeFences = true
  guessSyntax = true
  noClasses = false
  style = "catppuccin-macchiato"

[tableOfContents]
  startLevel = 1
  endLevel = 6
  ordered = false
